//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.Extensions.Configuration.UserSecrets.UserSecretsIdAttribute("aspnet-SocialNetwork.Web-31da818e-23bd-4e1a-a330-845c0bc3f759")]
[assembly: System.Reflection.AssemblyCompanyAttribute("SocialNetwork.Web")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+0b3a9c5f7107dd399b2339d43a0cf01ae3c82258")]
[assembly: System.Reflection.AssemblyProductAttribute("SocialNetwork.Web")]
[assembly: System.Reflection.AssemblyTitleAttribute("SocialNetwork.Web")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

